### ISSUE TITLE
Broken IR module since llvm 3.8

### ISSUE THREAD

**Issue by Chadi-akel** [benchmark-subsetting/cere#123]
Sometimes outlining a region breaks the IR module because debug informations refer to the old location of the region (before outlining). We temporarily fixed the problem by disabling the IR verifier pass after outlining. But this may hide other problems in the IR code.

The best way to do this is to rewrite the function `removeWrongMetadata` in file RegionExtractor.cpp for llvm 3.8 and greater and re-enable the IR verifier pass.

**Comment by pablooliveira** [comment]
I think this is fixed in #157 and could be closed. What do you think @Chadi-akel ?
