### ISSUE TITLE
Something is wrong on the nightly performance runs

### ISSUE THREAD

**Issue by pablooliveira** [benchmark-subsetting/cere#133]
Hi @Chadi-akel, something is wrong in the nightly runs. See for example, 

http://tahiti.prism.uvsq.fr/jenkins/job/loop-llvm-extractor-nightly/lastSuccessfulBuild/artifact/examples/NPB3.0-SER/BT/BT_ilp.html

Do you have any idea of what is going on ?

**Comment by Chadi-akel** [comment]
Hi @pablooliveira, according to the corresponding [log file](http://tahiti.prism.uvsq.fr/jenkins/job/loop-llvm-extractor-nightly/800/console) it looks like tracing regions is failing. I look in more detail as soon as possible.

**Comment by pablooliveira** [comment]
Thanks for the fix :+1:
