### ISSUE TITLE
Travis script not working as expected

### ISSUE THREAD

**Issue by Chadi-akel** [benchmark-subsetting/cere#14]
Make command fails to generate the documentation: ronn is not finding required libraries.
Tests are failing: probably due to old ubuntu version (12.04)

Maybe trying with trusty distribution can fix these issues.

**Comment by pablooliveira** [comment]
For ronn, have you tried installing ruby-rdiscount package, http://packages.ubuntu.com/fr/precise/ruby/ruby-rdiscount ? If that is the problem it should probably be added as a dependency in INSTALL.md.

For the test failing, could you please add something that prints the output of failed tests in .travis.yml. Something in the style of the following snipped should work:

``` shell
  - for i in $(find tests/ -maxdepth 1 -type d -name 'test_*' | sort ); do echo "************** TEST $i"; cat $i/test.log; done;
```

**Comment by pablooliveira** [comment]
There seems to be a final issue with numpy.random.choice() not being there. But you are very close !

**Comment by pablooliveira** [comment]
#17,#18 fixed most of the stuff. Last point remaining, .travis.yml should fail if any test in the testsuit fails.
