### ISSUE TITLE
CERE_REPLAY_REPETITIONS should be read at replay time not at compile time

### ISSUE THREAD

**Issue by pablooliveira** [benchmark-subsetting/cere#154]
There is no reason for CERE_REPLAY_REPETITIONS to be hardcoded at compile time. It would be much more convenient to have it read at replay time.

**Comment by Chadi-akel** [comment]
Yes you're right. I checked and it should be possible to modify replay repetitions without recompiling the codelet since this value is not even used in replay compilation passes.

**Comment by pablooliveira** [comment]
Ok great thanks for the feedback @Chadi-akel !
