### ISSUE TITLE
Fread fails at capture

### ISSUE THREAD

**Issue by Chadi-akel** [benchmark-subsetting/cere#168]
On Yales2, fread fails to read the file at capture time.
To reproduce this bug:

```bash
cd /home/cakel/yales2-mpire/
. env_yales.sh
export OMPI_CC=cerec
export OMPI_FC=cerec
cd avvt/ics_3D_cylinder/
cere capture --region=__cere__linear_solver_operators_m___linear_solver_operators_m_MOD_solve_linear_system_deflated_pcg_4386 -f --norun --invocation=1
./3D_cylinder
```

The error is:

<0>(3)      Reading gambit file without binary IO swapping.
<0>(3)      If trouble, set RESTART_GAMBIT_IOSWAP to TRUE.
<0>(3)      in complete_gambit_face_conn
<0>(3)    found            0  nodes
<0>(3)    found            0  elements
<0>(3)    found            0  faces
<0> 
ERROR: no i2 buffer to free
<0> Exiting...

A fix is to edit /home/cakel/yales2-mpire/src/main/gambit_bin_io_c.c in order to replace fread by read:
uncomment at line 36: //file_fd = open(filename, O_RDONLY);
comment line 266: byte_read = fread(char_buffer, sizeof(char), STRINGLEN, file_flag);
Uncomment line 267: //byte_read = read(file_fd, char_buffer, STRINGLEN);

**Comment by pablooliveira** [comment]
Thanks, I just tested and this is fixed in PR #169 at 1d4e841. I will finish the PR and close this bug.
