### ISSUE TITLE
Survey Question on the For loop in source file tests/test_11/lbm.c line 464

### ISSUE THREAD

**Issue by kishorev22** [benchmark-subsetting/cere#195]
Hello Sir/ Madam
We are from a research group at Iowa State University, USA. We want to do a survey on Github developers on the methods they used for paralleling their code. To do the survey, We want to ask three questions:

1. Have you ever tried to add pragma for that 'for' loop?.

2. How much confidence do you have about the correctness of this implementation? You can choose from 1-5 with 1 as the lowest confidence score and 5 as the highest confidence.

3. (Optional) Do you actually run (interpret the code with compilation and pass input/get output) the code? Yes/No
- If yes, can you provide the information of what are the input and expected output of this program (the input that caused the program to run through this for-loop).

The for loop is from line 464 of file https:/github.com/benchmark-subsetting/cere/blob/master/tests/test_11/lbm.c
Here is a part of the code:

nan
for (i = 0 + (N_CELL_ENTRIES * ((0 + (0 * (1 * 100))) + ((0 * (1 * 100)) * (1 * 100)))); i < (0 + (N_CELL_ENTRIES * ((0 + (0 * (1 * 100))) + ((130 * (1 * 100)) * (1 * 100))))); i += N_CELL_ENTRIES)
{
  rho = ((((((((((((((((((+grid[(C + (N_CELL_ENTRIES * ((0 + (0 * (1 * 100))) + ((0 * (1 * 100)) * (1 * 100))))) + i]) + grid[(N + (N_CELL_ENTRIES * ((0 + (0 * (1 * 100))) + ((0 * (1 * 100)) * (1 * 100))))) + i]) + grid[(S + (N_CELL_ENTRIES * ((0 + (0 * (1 * 100))) + ((0 * (1 * 100)) * (1 * 100)))))

Sincerely thanks

**Comment by pablooliveira** [comment]
Dear @kishorev22,

The line you are pointing at belongs to `lbm.c`, a benchmark that is not part of CERE. (the file belongs to the `tests/` directory)
Your questions should be addressed to the lbm authors instead.

Moreover, this is not an issue about CERE. Therefore, I would please request that you do not use this channel for your survey.
Questions such as these should be adressed to our mailing list as pointed in our documentation:
> For more general questions or discussions please use the [cere-dev@googlegroups.com mailing list](https://groups.google.com/forum/#!forum/cere-dev).

regards
