### ISSUE TITLE
CERE_OMP logic should be reworked

### ISSUE THREAD

**Issue by pablooliveira** [benchmark-subsetting/cere#45]
Currently, CERE performs OpenMP region capture if the environment variable CERE_OMP is set to 1.
I think it would be better to trigger OpenMP capture on a per workspace basis. This can be achieved by adding an `--openmp` option to `cere configure`. Then each time a pass is called it can check the current configuration and decide wheter loop or openmp extraction should be performed.

**Comment by pablooliveira** [comment]
@Chadi-akel: what is the status on this ? Did you have time to tackle it during your work to integrate openmp capture in development branch ?

**Comment by Chadi-akel** [comment]
@pablooliveira Yes it has been updated on the development branch, OpenMP capture can be triggered at cere configure step with --omp flag.

**Comment by pablooliveira** [comment]
Then we can close this issue ?

**Comment by Chadi-akel** [comment]
Fixed in #74
