### ISSUE TITLE
make install does not install cere-* utils

### ISSUE THREAD

**Issue by roachspray** [benchmark-subsetting/cere#6]
Perhaps I'm being a moron (very well possible!), make install is not installing the cere-\* wrapper utilities. It is installing the man pages fine.

**Comment by pablooliveira** [comment]
For now `make install` does not install the cere wrapper. I work around this by exporting cere root directory in my PATH environment variable. 

Nevertheless implementing support for make install should not be too hard, thanks for reporting the issue. If you want to work on this, we would gladly accept a pull request too :-)

**Comment by roachspray** [comment]
@pablooliveira Thanks for the tip. I may do the pull req (depending on time within the next couple of weeks, hopefully? haha.. work :-/). Thank you for making the code available.
