### ISSUE TITLE
cere report fails if table_error.csv is missing

### ISSUE THREAD

**Issue by pablooliveira** [benchmark-subsetting/cere#99]
cere report fails if table_error.csv is missing. It would be nice to send a nice message that cere check-matching must be run.

```
INFO 07/22/2016 17:49:37 CERE : Start
INFO 07/22/2016 17:49:37 Report : Start report
WARNING 07/22/2016 17:49:37 Report : Can't find .cere/report/table_error.csv
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/test/lib/python2.7/site-packages/cere/__main__.py", line 88, in <module>
    if not cere_plugins[args.mode](args):
  File "/tmp/test/lib/python2.7/site-packages/cere/cere_report.py", line 478, in run
    REPORT = Report(bench, graph, args.mincycles)
  File "/tmp/test/lib/python2.7/site-packages/cere/cere_report.py", line 184, in __init__
    self._part = graph.graph['coverage']
KeyError: 'coverage'
```

**Comment by Chadi-akel** [comment]
Actually the python error is not because of the missing table_error.csv file. This file is not mandatory and it's just a warning.
The error is because coverage is missing in the graph. But it seems you already run cere profile so I am curious how you got this error. Do you have an empty graph?

**Comment by pablooliveira** [comment]
I got this error when writing a new test for check-io. I had already run: cere configure, cere regions and cere capture. Then I tried to run cere report and this error triggered.

I had not run cere profile in this case.

**Comment by Chadi-akel** [comment]
Maybe you have an old graph_.pkl in .cere/profile because cere regions should warn you that you don't have profiled the application yet, and report should print an error:

$cere report
INFO 07/26/2016 17:36:37 CERE : Start
INFO 07/26/2016 17:36:37 Report : Start report
CRITICAL 07/26/2016 17:36:37 Report : Can't load graph. Did you run cere profile?
INFO 07/26/2016 17:36:37 CERE : Stop

So maybe you have an old format graph with missing attributes.

**Comment by pablooliveira** [comment]
Nope sorry after checking it seems I did run "cere profile". As discussed it's an empty graph issue.
